### ISSUE TITLE
road to v0.2.0

### ISSUE THREAD

**Issue by yjlintw** [yjlintw/comic-reader#73]
# Top Priority
- [x] ~~**[Read-View]** Read area zoom mode~~ (PR #74)
 - http://ignitersworld.com/lab/imageViewer.html
- [x] ~~**[Search-View]** Search filter~~ (PR #74)
- [ ] **[Developing]** Add testing (#11)
 - https://electron.atom.io/spectron/
- [ ] **[Developing]** Edit documentation (#20)
- [x] ~~**[Overall]** Fixed Mobile View~~ (#75, PR #94)
- [ ] **[Developing]** Error/Exception handling  (#76)
- [x] ~~**[Other]** Make an official website~~ 

# Medium Priority
- [x] **[Read-View]** Indicators shows that the user has reached the end of the page (#77, PR #113 )
- [x] ~~**[Read-View]** Right click to save image~~ (PR #85)
- [ ] **[Read-View]** Read/Unread chapters' colors are not very distinguishable (#78)
- [x] ~~**[System]** Notification's icon~~ (PR #90)
- [x] ~~**[Bug]** Scrollbar is not draggable under Windows~~ (PR #86)
- [x] ~~**[System]** Add confirmation dialog box when update is available~~

# Low Priority
- [x] ~~**[App]** Dedicated titlebar for both Windows and Mac~~ (#80, PR#95, PR #98, PR #100)
- [ ] (**Postponed**) **[Read-View]** Read area fullscreen mode 
- [ ] (**Postponed**) **[Read-View]** Remember the last read page for every chapter, not just for the chapter user read last 
- [ ] (**Postponed**) **[Read-View]** Right click to reload a single image 
- [ ] (**Postponed**) **[System]** Add downloading progress bar when downloading new updates
  - The autoupdater we use does not have download progress information for mac
